version: 0.2

env:
  secrets-manager:
    SERVERLESS_ACCESS_KEY: "sls/keys/serverless"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install -g serverless

  pre_build:
    commands:
      - echo Running pre-build commands...
#      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm install

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running post-build commands...
#      - serverless login
      - serverless deploy --stack sls-test-s

artifacts:
  files:
    - '**/*'
  discard-paths: yes