# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: davidcher
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sls-first

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  memorySize: 512
  timeout: 10
  stackName: sls-first-stack

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources: # CloudFormation template syntax
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userInfoTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: info
            AttributeType: S
          - AttributeName: createdDt
            AttributeType: N
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: createdDt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1